### ISSUE TITLE
Issue building

### ISSUE THREAD

**Issue by calvertdw** [ros2-java/ament_java#6]
On Windows and Linux I'm getting the error:

```
~/rosdev/ament_ws$ python3 src/ament/ament_tools/scripts/ament.py build --symlink-install --isolated
Traceback (most recent call last):
  File "src/ament/ament_tools/scripts/ament.py", line 139, in <module>
    from ament_tools.package_types.ament import entry_point_data as ament_entry_point_data  # noqa
  File "/home/shadylady/rosdev/ament_ws/src/ament/ament_tools/ament_tools/package_types/ament.py", line 15, in <module>
    from catkin_pkg.package import package_exists_at
ImportError: No module named 'catkin_pkg'
```

**Comment by esteve** [comment]
There's been a few changes in the build system upstream and now
python-catkin-pkg-modules needs to be installed as well.

Can you try again after doing apt-get install python-catkin-pkg-modules on
Ubuntu and pip install catkin-pkg-modules on Windows?

>

**Comment by calvertdw** [comment]
It worked! Thanks a bunch.

**Comment by esteve** [comment]
@calvertdw Any time!
